import Head from 'next/head'
import Login from './Login'
import Discover from './Discover';
import { useRouter } from "next/router";

export default function Home() {
  const route = useRouter();
	const { code } = route.query;

  return (
    <>
      <Head>
        <title>Groovehub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        {code ? <Discover code={code} /> : <Login />}
      </main>
    </>
  )
}
